### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [Kashiwara0205/thunderGirl#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by Kashiwara0205** [comment]
Hey！
thanks for your issues.
I'm really interested about  type-checking feature.
Yes, I'll be happy with that.

My English may be a little strange, because I am Japanese.
I'm sorry if my English is difficult to understand.

**Comment by geopic** [comment]
I will start on it then. Your English is good :+1:
